pure_pursuit_node:
  ros__parameters:
    enable_vis: true
    waypoint_filename: "wu_chen_straight_line_spline_3.csv"
    map_frame: "map"
    drive_topic: "/drive"
    pose_topic: "/ego_racecar/odom"
    waypoint_vis_topic: "/waypoint_vis"
    track_waypoint_vis_topic: "/track_waypoint_vis"
    look_ahead_dist:  1.0
    window_size:  4
    viable_dist:  14.0
    steering_gain:  0.7
    max_speed: 2.0